In [1]:
import pandas as pd

In [7]:
xlsfile = pd.ExcelFile('/Users/DrithnChakrav/Desktop/Time-Sheets/Drithin_November_ TImesheets.xlsx')

In [9]:
dframe = xlsfile.parse() #We parse the excel file and assign to a data frame, we can give specific sheets inside excel 
#in the parse() bracket to parse into a data frame

In [10]:
dframe

    Unnamed: 0                                       INSTRUCTIONS
0          NaN                                                NaN
1          NaN  Timesheets and receipts must be completed and ...
2          NaN                                                NaN
3          NaN                                                NaN
4          NaN                                                NaN
5          NaN       Only enter data into the light YELLOW cells.
6          NaN                                                NaN
7          NaN  Only enter your name, time period, client name...
8          NaN                                                NaN
9          NaN  Time is entered in hours.  Do not enter anythi...
10         NaN                                                NaN
11         NaN  Use the Notes sections for general notes and c...
12         NaN                                                NaN
13         NaN  Allocate all expenses at the bottom of the exp...
14         NaN                                                NaN
15         NaN  This worksheet will accomodate up to 8 client ...
16         NaN                                                NaN
17         NaN  Enter nothing into the summary worksheet.  Thi...
18         NaN                                                NaN
19         NaN  All subcontractors are required to complete an...
20         NaN                                                NaN
21         NaN  Enter rate and payment information into the wh...
22         NaN                                                NaN
23         NaN  Do not cut and paste cells or insert/delete ro...
24         NaN                                                NaN
25         NaN  Contact Jim Nichols for chargecodes not listed...